### ISSUE TITLE
race condition causes cluster to fail

### ISSUE THREAD

**Issue by stevendborrelli** [asteris-llc/docker-zookeeper#3]
Including @ChrisAubuchon 

When the health check fails, the consul query will not populate the environment file with the servers that fail the health check.

This causes missing entries in the zk configuration, which means if a server is attempting to start and doesn't see its configuration it will never start.

**Comment by stevendborrelli** [comment]
I believe we can set the service lookup to "passing,warning" and use the following check setup in consul:
zookeeper not running -> exit 2
|| stat not "imok" -> exit 1 
|| stat "imok" -> exit 0

**Comment by stevendborrelli** [comment]
Fixed in 8826d47e2082109635b008506b1536a5cb959e67

**Comment by simonvanderveldt** [comment]
@stevendborrelli did this actually fix the issue for you? Because if an instance fails it's health-check it makes sense to not include it in the list of working instances, right?

Do you still use this project btw? It hasn't seen activity in a long time.
